//
// Generated file, do not edit! Created by nedtool 5.4 from serverStatusUpdate.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SERVERSTATUSUPDATE_M_H
#define __SERVERSTATUSUPDATE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>serverStatusUpdate.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ServerStatusUpdate
 * {
 *     int serverId;
 *     bool busy;
 * }
 * </pre>
 */
class ServerStatusUpdate : public ::omnetpp::cPacket
{
  protected:
    int serverId;
    bool busy;

  private:
    void copy(const ServerStatusUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ServerStatusUpdate&);

  public:
    ServerStatusUpdate(const char *name=nullptr, short kind=0);
    ServerStatusUpdate(const ServerStatusUpdate& other);
    virtual ~ServerStatusUpdate();
    ServerStatusUpdate& operator=(const ServerStatusUpdate& other);
    virtual ServerStatusUpdate *dup() const override {return new ServerStatusUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getServerId() const;
    virtual void setServerId(int serverId);
    virtual bool getBusy() const;
    virtual void setBusy(bool busy);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ServerStatusUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ServerStatusUpdate& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SERVERSTATUSUPDATE_M_H

